apiVersion: v1
kind: Service
metadata:
  name: license-validation-service
  namespace: default
  labels:
    app: license-validation-service
spec:
  selector:
    app: license-validation-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
      protocol: TCP
      appProtocol: grpc
    - name: http-management
      port: 8080
      targetPort: 8080
      protocol: TCP
